---
name: Run pytest tests

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "*.md"
      - ".gitignore"

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: 0.4.27

      - name: Install project with uv
        run: uv sync --all-extras --dev

      - name: Run pytest tests
        run: uv run nox -s tests
